export const carBrands = [
    "Audi",
    "Chevrolet",
    "Citroen",
    "Fiat",
    "Ford",
    "Volkswagen",
    "Nissan",
    "Jeep",
    "Mini",
    "Honda",
    "Porsche",
    "Peugeot",
    "Renault",
    "Mercedes-Benz",
    "BMW",
    "Dodge",
    "Chery",
    "Land Rover",
    "Toyota",
    "Suzuki",
    "Chrysler",
    "Harley davidson",
    "Opel",
    "Hyundai",
    "Kia",
    "Ktm",
    "Benelli",
    "Yamaha"
]